### ISSUE TITLE
Desenvolvimento do Protótipo Figma inicial

### ISSUE THREAD

**Issue by devMarcosVM** [mdsreq-fga-unb/2024.2-T03-PanelasGrill#32]
## **Descrição**  
Criar um protótipo inicial no Figma para representar a interface do sistema de gerenciamento de estoque e fluxo de caixa. Este protótipo deve fornecer uma visão geral da estrutura e funcionalidade básica do sistema, com foco em usabilidade e experiência do usuário (UX). O objetivo é permitir validação visual das telas antes de iniciar a implementação do sistema.  

**Pontos principais a serem abordados no protótipo:**  
- Tela de login.  
- Tela de Menu
---

### **Tarefas**  

- [x] **Tarefa 1:** Criar a estrutura da tela de login com campos de usuário, senha e botão "Entrar".    
- [x] **Tarefa 2:** Criação do protótipo do Menu do site.

### **Resultados Esperados** 
- Interface intuitiva e fácil de usar para validação inicial do fluxo de navegação.  
- Ajustes realizados com base no feedback para alinhar expectativas antes do desenvolvimento.

**Comment by antonioleaojr** [comment]
Finalizamos a implementação inicial no figma, contemplando as duas tarefas da issue.
